### ISSUE TITLE
Rebuilder (Music replacement version) errors when clicking "Run"

### ISSUE THREAD

**Issue by DiskyNorsk** [itsmattkc/LEGOIslandRebuilder#76]
i don't know if it has anything with the app version to do, but whenever i click Run, this error pops up
![Skjermbilde (66)](https://github.com/itsmattkc/LEGOIslandRebuilder/assets/110564749/dd4d361b-1b55-4eb1-9525-f51e9b9a4917)
The error says it couldn't find ISLE.EXE at %Temp%\LEGOIslandRebuilder\, and if i put ISLE.EXE into the folder, for some reason it deletes ISLE.EXE and throws the exact same error. 

if it helps, here's the error log it spat out (translated to english from norwegian by me by me):

    See the end of this message for detailed info on activating
    JIT-debugging (Just In Time) instead of this dialog.

    ************** Exception text **************
    System.IO.FileNotFoundException: Could not find the file C:\Users\{user}\AppData\Local\Temp\LEGOIslandRebuilder\ISLE.EXE.
    Filname: C:\Users\{user}\AppData\Local\Temp\LEGOIslandRebuilder\ISLE.EXE
    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
    at System.IO.File.Open(String path, FileMode mode, FileAccess access)
    at Rebuilder.Rebuilder.Patch(String source_dir, String dir)
    at Rebuilder.Rebuilder.LaunchGame()
    at System.Windows.Forms.Control.OnClick(EventArgs e)
    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
    at System.Windows.Forms.Control.WndProc(Message& m)
    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
    at System.Windows.Forms.Button.WndProc(Message& m)
    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

    ************** Loaded collections **************
    mscorlib
        Collection version: 2.0.0.0
        Win32-version: 2.0.50727.9174 (WinRelRS6.050727-9100)
        CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
    ----------------------------------------
    Rebuilder
        Collection version: 0.0.0.0
        Win32-version: 0.0.0.0
        CodeBase: file:///C:/Users/{user}/Downloads/Rebuilder%20(with%20music%20replacement).exe
    ----------------------------------------
    System.Windows.Forms
        Collection version: 2.0.0.0
        Win32-version: 2.0.50727.9157 (WinRelRS6.050727-9100)
        CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
    ----------------------------------------
    System
        Collection version: 2.0.0.0
        Win32-version: 2.0.50727.9171 (WinRelRS6.050727-9100)
        CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
    ----------------------------------------
    System.Drawing
        Collection version: 2.0.0.0
        Win32-version: 2.0.50727.9157 (WinRelRS6.050727-9100)
        CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
    ----------------------------------------
    System.Windows.Forms.resources
        Collection version: 2.0.0.0
        Win32-version: 2.0.50727.9157 (WinRelRS6.050727-9100)
        CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_no_b77a5c561934e089/System.Windows.Forms.resources.dll
    ----------------------------------------
    System.Xml
        Collection version: 2.0.0.0
        Win32-version: 2.0.50727.9157 (WinRelRS6.050727-9100)
        CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
    ----------------------------------------
    System.Configuration
        Collection version: 2.0.0.0
        Win32-version: 2.0.50727.9157 (WinRelRS6.050727-9100)
        CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
    ----------------------------------------
    7abx-rcb
        Collection version: 0.0.0.0
        Win32-version: 2.0.50727.9171 (WinRelRS6.050727-9100)
        CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
    ----------------------------------------
    System.resources
        Collection version: 2.0.0.0
        Win32-version: 2.0.50727.9157 (WinRelRS6.050727-9100)
        CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.resources/2.0.0.0_no_b77a5c561934e089/System.resources.dll
    ----------------------------------------
    mscorlib.resources
        Collection version: 2.0.0.0
        Win32-version: 2.0.50727.9174 (WinRelRS6.050727-9100)
        CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
    ----------------------------------------

    ************** JIT-debugging **************
    Når du skal aktivere JIT-debugging (Just In Time), må .config-filen for dette
    programmet eller datamaskinen (machine.config) ha
    jitDebugging-verdien angitt i delen system.windows.forms.
    Programmet må også kompileres med debugging
    aktivert.

    For example:

    <configuration>
        <system.windows.forms jitDebugging="true" />
    </configuration>

    Når JIT-debugging er aktivert, blir alle ubehandlede unntak
    sendt til the JIT-debugging som er registrert på datamaskinen,
    i stedet for å bli behandlet av denne dialogboksen.

if you need further info to help me, please do ask

**Comment by VoxelTek** [comment]
I know this doesn't solve the issue, but maybe consider looking into [SIedit](https://github.com/itsmattkc/SIEdit)? It's more capable and better updated, and it does allow the substitution of audio files within the game. It would allow you to use the more modern Rebuilder version while also updating the music if you wish.
